typealias Hdwf Cint

@enum(ENUMFILTER,
  ENUMFILTERALL=0,
  ENUMFILTEREEXPLORER=1,
  ENUMFILTERDISCOVERY=2)

@enum(DEVID,
  DEVIDEEXPLORER=0,
  DEVIDDISCOVERY=1,
  DEVIDDISCOVERY2=2)

@enum(DEVVER,
  DEVVEREEXPLORERCDISCOVERYB=2,
  DEVVEREEXPLORERE=4,
  DEVVEREEXPLORERF=5,
  DEVVERDISCOVERYA=1,
  DEVVERDISCOVERYC=3)

@enum(DWFENUMCONFIGINFO,
  DECIANALOGINCHANNELCOUNT=1,
  DECIANALOGOUTCHANNELCOUNT=2,
  DECIANALOGIOCHANNELCOUNT=3,
  DECIDIGITALINCHANNELCOUNT=4,
  DECIDIGITALOUTCHANNELCOUNT=5,
  DECIDIGITALIOCHANNELCOUNT=6,
  DECIANALOGINBUFFERSIZE=7,
  DECIANALOGOUTBUFFERSIZE=8,
  DECIDIGITALINBUFFERSIZE=9,
  DECIDIGITALOUTBUFFERSIZE=0)

@enum(DWFSTATE,
  DWFSTATEREADY=0,
  DWFSTATECONFIG=4,
  DWFSTATEPREFILL=5,
  DWFSTATEARMED=1,
  DWFSTATEWAIT=7,
  DWFSTATETRIGGEREDRUNNING=3,
  DWFSTATEDONE=2)

@enum(ACQMODE,
ACQMODESINGLE=0,
ACQMODESCANSHIFT=1,
ACQMODESCANSCREEN=2,
ACQMODERECORD=3)

@enum(FILTER,
FILTERDECIMATE=0,
FILTERAVERAGE=1,
FILTERMINMAX=2)


@enum(TRIGSRC,
TRIGSRCNONE=0,
TRIGSRCPC=1,
TRIGSRCDETECTORANALOGIN=2,
TRIGSRCDETECTORDIGITALIN=3,
TRIGSRCANALOGIN=4,
TRIGSRCDIGITALIN=5,
TRIGSRCDIGITALOUT=6,
TRIGSRCANALOGOUT1=7,
TRIGSRCANALOGOUT2=8,
TRIGSRCANALOGOUT3=9,
TRIGSRCANALOGOUT4=10,
TRIGSRCEXTERNAL1=11,
TRIGSRCEXTERNAL2=12,
TRIGSRCEXTERNAL3=13,
TRIGSRCEXTERNAL4=14)

@enum(DWFANALOGOUTMODE,
DWFANALOGOUTMODEVOLTAGE=0,
DWFANALOGOUTMODECURRENT=1)

@enum(DWFANALOGOUTIDLE,
DWFANALOGOUTIDLEDISABLE=0,
DWFANALOGOUTIDLEOFFSET=1,
DWFANALOGOUTIDLEINITIAL=2)

@enum(ANALOGOUTNODE,
ANALOGOUTNODECARRIER=0,
ANALOGOUTNODEFM=1,
ANALOGOUTNODEAM=2)

@enum(FUNC,
FUNCDC=0,
FUNCSINE=1,
FUNCSQUARE=2,
FUNCTRIANGLE=3,
FUNCRAMPUP=4,
FUNCRAMPDOWN=5,
FUNCNOISE=6,
FUNCCUSTOM=30,
FUNCPLAY=31)
